#!/bin/sh

# Configuration Wi-Fi
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].disabled='0'
uci set wireless.@wifi-iface[0].encryption='none'
uci set wireless.@wifi-iface[0].ssid='OpenWrt_2.4G'

uci set wireless.@wifi-device[1].disabled='0'
uci set wireless.@wifi-iface[1].disabled='0'
uci set wireless.@wifi-iface[1].encryption='none'
uci set wireless.@wifi-iface[1].ssid='OpenWrt_5G'

uci commit wireless

# Activer le flow offloading
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'
uci commit firewall

# Activer le WED pour le pilote mt7915e
mkdir -p /etc/modules.d
cat >/etc/modules.d/mt7915e <<'EOF'
mt7915e wed_enable=Y
EOF

sync
reboot

exit 0
